### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by cyberbeast** [b3ntly/ng2-gRPC#2]
Would you happen to have an article/blog post or maybe even a tutorial that explains the usage?

**Comment by beeekind** [comment]
Thanks, no blog post and this project is pretty out of date. I've been out of gRPC land for awhile and understand angular and grpc-web have both progressed quite a bit (my guess is all the angular stuff would break if you were to update it).

If you're interested I'd recommend starting a modern version of this project from scratch using updated dependencies and seeing where that takes you. gRPC > REST in my book and who knows maybe its matured enough to merit its use in production grade web applications.
